import { MetaLead, DropdownSettings, StatusConfig } from '../types/crm';

export const DEFAULT_STATUSES: StatusConfig[] = [
  { key: 'Interested', label: 'Interested', color: '#8b5cf6', bgLight: 'bg-purple-50 dark:bg-purple-950/40', borderLight: 'border-purple-200 dark:border-purple-800' },
  { key: 'Pitched', label: 'Pitched', color: '#3b82f6', bgLight: 'bg-blue-50 dark:bg-blue-950/40', borderLight: 'border-blue-200 dark:border-blue-800' },
  { key: 'Call Back', label: 'Call Back', color: '#f59e0b', bgLight: 'bg-amber-50 dark:bg-amber-950/40', borderLight: 'border-amber-200 dark:border-amber-800' },
  { key: 'Registration', label: 'Registration', color: '#10b981', bgLight: 'bg-emerald-50 dark:bg-emerald-950/40', borderLight: 'border-emerald-200 dark:border-emerald-800' },
  { key: 'Not Interested', label: 'Not Interested', color: '#ef4444', bgLight: 'bg-rose-50 dark:bg-rose-950/40', borderLight: 'border-rose-200 dark:border-rose-800' },
];

export const DEFAULT_MODULES: string[] = [
  'SAP',
  'AWS',
  'CLOUD COMPUTING SUITE',
  'DATA SCIENCE',
  'DATA ANALYTICS',
  'AI',
];

export const DEFAULT_HR_NAMES: string[] = [
  'Priya Sharma',
  'Rahul Verma',
  'Ananya Iyer',
  'Vikram Malhotra',
  'Sneha Patel',
];

export const DEFAULT_DROPDOWN_SETTINGS: DropdownSettings = {
  modules: DEFAULT_MODULES,
  hrNames: DEFAULT_HR_NAMES,
  statuses: DEFAULT_STATUSES,
};

export const INITIAL_LEADS: MetaLead[] = [
  {
    id: 'lead-1',
    name: 'Aarav Mehta',
    phone: '+91 98765 43210',
    email: 'aarav.mehta@gmail.com',
    module: 'DATA SCIENCE',
    dateOfLead: '2026-09-14',
    timeOfLead: '09:30 AM',
    campaignName: 'Meta_DataScience_Sept26',
    adsetName: 'Graduates_Engineers_21_28',
    adName: 'Ad_Video_CareerSalaryHike_V1',
    hrName: 'Priya Sharma',
    status: 'Interested',
    callBackTime: '',
    notes: 'Inquiring about weekend live classes and Python prerequisites.',
    createdAt: '2026-09-14T09:30:00Z',
    isProcessed: true,
    callReports: [
      {
        id: 'cr-1',
        leadId: 'lead-1',
        hrName: 'Priya Sharma',
        statusAtCall: 'Interested',
        remarks: 'Candidate is working in manual QA, wants to transition to Data Science. Shared curriculum PDF on WhatsApp.',
        createdAt: '2026-09-14T11:15:00Z',
      }
    ],
  },
  {
    id: 'lead-2',
    name: 'Rohan Deshmukh',
    phone: '+91 91234 56789',
    email: 'rohan.d@yahoo.com',
    module: 'AWS',
    dateOfLead: '2026-09-15',
    timeOfLead: '02:20 PM',
    campaignName: 'Meta_Cloud_AWS_Leads_Sept',
    adsetName: 'IT_Professionals_SysAdmins',
    adName: 'Ad_Carousel_AWS_SolutionsArchitect',
    hrName: 'Rahul Verma',
    status: 'Call Back',
    callBackTime: '2026-09-16T17:30',
    notes: 'Requested callback after office hours at 5:30 PM.',
    createdAt: '2026-09-15T14:20:00Z',
    isProcessed: true,
    callReports: [
      {
        id: 'cr-2',
        leadId: 'lead-2',
        hrName: 'Rahul Verma',
        statusAtCall: 'Call Back',
        callBackTime: '2026-09-16T17:30',
        remarks: 'Spoke briefly. He was in a scrum meeting, asked to call back today at 5:30 PM sharp.',
        createdAt: '2026-09-15T15:00:00Z',
      }
    ],
  },
  {
    id: 'lead-3',
    name: 'Kavita Nair',
    phone: '+91 99887 76655',
    email: 'kavita.nair@outlook.com',
    module: 'AI',
    dateOfLead: '2026-09-12',
    timeOfLead: '10:00 AM',
    campaignName: 'Meta_GenerativeAI_LeadGen',
    adsetName: 'Developers_Python_AI_Enthusiasts',
    adName: 'Ad_Static_BuildLLMApps_Banner',
    hrName: 'Ananya Iyer',
    status: 'Registration',
    callBackTime: '',
    notes: 'Paid registration token amount for the upcoming October cohort!',
    createdAt: '2026-09-12T10:00:00Z',
    isProcessed: true,
    callReports: [
      {
        id: 'cr-3',
        leadId: 'lead-3',
        hrName: 'Ananya Iyer',
        statusAtCall: 'Pitched',
        remarks: 'Explained course modules: LLM fine-tuning, RAG architecture, LangChain.',
        createdAt: '2026-09-12T11:00:00Z',
      },
      {
        id: 'cr-4',
        leadId: 'lead-3',
        hrName: 'Ananya Iyer',
        statusAtCall: 'Registration',
        remarks: 'Enrolled! Payment confirmation receipt sent to her email.',
        createdAt: '2026-09-13T16:00:00Z',
      }
    ],
  },
  {
    id: 'lead-4',
    name: 'Suresh Reddy',
    phone: '+91 97654 32109',
    email: 'suresh.reddy@gmail.com',
    module: 'SAP',
    dateOfLead: '2026-09-13',
    timeOfLead: '12:45 PM',
    campaignName: 'Meta_SAP_ERP_Campaign',
    adsetName: 'Finance_SupplyChain_Pros',
    adName: 'Ad_Video_SAPHana_Certification',
    hrName: 'Vikram Malhotra',
    status: 'Pitched',
    callBackTime: '',
    notes: 'Pitched SAP FICO & MM modules. Checking with company for sponsorship.',
    createdAt: '2026-09-13T12:45:00Z',
    isProcessed: true,
    callReports: [
      {
        id: 'cr-5',
        leadId: 'lead-4',
        hrName: 'Vikram Malhotra',
        statusAtCall: 'Pitched',
        remarks: 'Detailed 15-min counseling call. Shared brochure and certification roadmap.',
        createdAt: '2026-09-13T15:30:00Z',
      }
    ],
  },
  {
    id: 'lead-5',
    name: 'Neha Kulkarni',
    phone: '+91 93456 78901',
    email: 'neha.kulkarni@gmail.com',
    module: 'DATA ANALYTICS',
    dateOfLead: '2026-09-15',
    timeOfLead: '08:10 AM',
    campaignName: 'Meta_DataAnalytics_PowerBI',
    adsetName: 'BCom_BBA_NonTech_Grads',
    adName: 'Ad_Reel_PowerBI_SQL_Portfolio',
    hrName: 'Sneha Patel',
    status: 'Call Back',
    callBackTime: '2026-09-16T16:00',
    notes: 'Wants to know placement assistance details and mock interview schedule.',
    createdAt: '2026-09-15T08:10:00Z',
    isProcessed: true,
    callReports: [
      {
        id: 'cr-6',
        leadId: 'lead-5',
        hrName: 'Sneha Patel',
        statusAtCall: 'Call Back',
        callBackTime: '2026-09-16T16:00',
        remarks: 'Scheduled call back today at 4 PM to discuss placement tie-ups and student project reviews.',
        createdAt: '2026-09-15T10:30:00Z',
      }
    ],
  },
  {
    id: 'lead-6',
    name: 'Manish Pandey',
    phone: '+91 94567 12345',
    email: 'manish.p@gmail.com',
    module: 'CLOUD COMPUTING SUITE',
    dateOfLead: '2026-09-11',
    timeOfLead: '04:00 PM',
    campaignName: 'Meta_Cloud_AWS_Leads_Sept',
    adsetName: 'IT_Professionals_SysAdmins',
    adName: 'Ad_Carousel_AWS_SolutionsArchitect',
    hrName: 'Rahul Verma',
    status: 'Not Interested',
    callBackTime: '',
    notes: 'Already enrolled in college Masters program. Not looking for additional courses right now.',
    createdAt: '2026-09-11T16:00:00Z',
    isProcessed: true,
    callReports: [
      {
        id: 'cr-7',
        leadId: 'lead-6',
        hrName: 'Rahul Verma',
        statusAtCall: 'Not Interested',
        remarks: 'Candidate stated no budget and no time. Marked Not Interested.',
        createdAt: '2026-09-12T09:40:00Z',
      }
    ],
  },
  // UNTOUCHED LEADS (Only Name, Phone, Email, Campaign Details, Module, Date & Time autofilled. Counselor unassigned, Status untouched!)
  {
    id: 'meta-1628064518663536',
    name: 'SIVAKUMAR',
    phone: '+91 96007 23986',
    email: 'siva16386@gmail.com',
    module: 'SAP',
    dateOfLead: '2026-09-16',
    timeOfLead: '04:22 PM',
    campaignName: 'SAP - CBO - SEP 15',
    adsetName: 'SAP - CORE - SEP 15',
    adName: 'SAP CORE  IMAGE',
    formName: 'SAP SEP 15',
    platform: 'fb',
    city: 'gingee',
    customQuestions: 'Course: sap fico • Status: working professional • Start: immediately • Education: Bachelor\'s degree',
    hrName: '',
    status: 'Untouched',
    callBackTime: '',
    notes: 'Meta Form Responses: Course: sap fico • Status: working professional • Start: immediately • Education: Bachelor\'s degree • City: gingee',
    createdAt: '2026-09-16T16:22:55+05:30',
    isProcessed: false,
    callReports: [],
  },
  {
    id: 'untouched-1',
    name: 'Pooja Agarwal',
    phone: '+91 98111 22233',
    email: 'pooja.a@gmail.com',
    module: 'SAP',
    dateOfLead: '2026-09-16',
    timeOfLead: '08:00 AM',
    campaignName: 'Meta_SAP_ERP_Campaign',
    adsetName: 'Finance_SupplyChain_Pros',
    adName: 'Ad_Video_SAPHana_Certification',
    hrName: '',
    status: 'Untouched',
    callBackTime: '',
    notes: 'Autofilled from Meta Instant Form. Awaiting counselor assignment and first call.',
    createdAt: '2026-09-16T08:00:00Z',
    isProcessed: false,
    callReports: [],
  },
  {
    id: 'untouched-2',
    name: 'Arjun Singhania',
    phone: '+91 98234 55678',
    email: 'arjun.singhania@techmail.com',
    module: 'AI',
    dateOfLead: '2026-09-16',
    timeOfLead: '09:15 AM',
    campaignName: 'Meta_GenerativeAI_LeadGen',
    adsetName: 'Developers_Python_AI_Enthusiasts',
    adName: 'Ad_Static_BuildLLMApps_Banner',
    hrName: '',
    status: 'Untouched',
    callBackTime: '',
    notes: 'Autofilled from Instagram Lead Ad. Needs curriculum and batch timetable.',
    createdAt: '2026-09-16T09:15:00Z',
    isProcessed: false,
    callReports: [],
  },
  {
    id: 'untouched-3',
    name: 'Deepika Sen',
    phone: '+91 97112 34567',
    email: 'deepika.sen@gmail.com',
    module: 'DATA ANALYTICS',
    dateOfLead: '2026-09-16',
    timeOfLead: '10:05 AM',
    campaignName: 'Meta_DataAnalytics_PowerBI',
    adsetName: 'BCom_BBA_NonTech_Grads',
    adName: 'Ad_Reel_PowerBI_SQL_Portfolio',
    hrName: '',
    status: 'Untouched',
    callBackTime: '',
    notes: 'Autofilled from Facebook Lead Ad. Fresh inquiry received 30 mins ago.',
    createdAt: '2026-09-16T10:05:00Z',
    isProcessed: false,
    callReports: [],
  },
  {
    id: 'untouched-4',
    name: 'Karthik Raja',
    phone: '+91 96554 43322',
    email: 'karthik.raja@outlook.com',
    module: 'CLOUD COMPUTING SUITE',
    dateOfLead: '2026-09-16',
    timeOfLead: '10:45 AM',
    campaignName: 'Meta_Cloud_AWS_Leads_Sept',
    adsetName: 'IT_Professionals_SysAdmins',
    adName: 'Ad_Carousel_AWS_SolutionsArchitect',
    hrName: '',
    status: 'Untouched',
    callBackTime: '',
    notes: 'Autofilled from Meta Ads Manager leadgen webhook.',
    createdAt: '2026-09-16T10:45:00Z',
    isProcessed: false,
    callReports: [],
  },
];
